---
title: "NYC Restaurant Inspections "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(janitor)
library(tidytext)
library(stringr)
library(forcats)
library(viridisLite)
library(viridis)
library(lubridate)
```

```{r setup_data, cache = TRUE}

# Read NYC inspections data
nyc_inspections = read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz",
                           col_types = "cccccccccccccccccc", na = c("NA", "N/A")) %>%
  clean_names() %>%
  arrange(inspection_date, camis)

# Tidy up the inspections data
tidy_restaurant = nyc_inspections %>%  
  filter(grade %in% c("A", "B", "C") & 
       !boro %in% "Missing") %>% 
  # Also remove cuisine description
  filter(cuisine_description != " Not Listed/Not Applicable") %>%
  separate(inspection_date, into = c("date", "remove"), sep ="T")%>%
  select(-remove)%>%
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro),
         id = camis,
         cusin = cuisine_description,
         month = months(as.Date(date)),
         month = factor(month, levels = month.name),
         year = as.numeric(substr(date, 1, 4))) %>% 
  select(inspection_num, id, date, month, year, boro, grade, score, dba, 
         cusin, street, zipcode, violation_description, critical_flag, inspection_type,
         violation_code, action)

# Create dataset with distinct inspection dates, types, and camis(restaurant_ID)
distinct_restaurants = tidy_restaurant %>%
  distinct(date, inspection_type, id, .keep_all = TRUE) %>%
  arrange(date, inspection_type) %>%
  filter(date != "1900-01-01" & substr(date, 1, 4) != "2012") %>%
  mutate(score = as.numeric(score))

# Create dataset that counts number of violations per restaurant 
violations = tidy_restaurant %>%
  filter(date != "1900-01-01" & substr(date, 1, 4) != "2012" & !is.na(violation_code)) %>%
  group_by(id, date, cusin) %>%
  count()

# Data for association between number of restaurants of cuisine type vs. proportion of critical flags

# Number of restaurants in each cuisine type
  ncuisines = distinct_restaurants %>%
    group_by(cusin) %>%
    count() %>%
    rename(nresto = n)
  
# Number of violations 
  violations = tidy_restaurant %>%
    filter(date != "1900-01-01" & substr(date, 1, 4) != "2012" & !is.na(violation_code)) %>%
    group_by(id, date, cusin) %>%
    count() %>%
    rename(nviolations = n) %>%
    # For restaurants that were inspected multiple times, get median number of violations
    group_by(id, cusin) %>%
    summarize(mdn_violations = median(nviolations),
              min_violations = min(nviolations),
              max_violations = max(nviolations)) %>%
    # Take the median number of violations 
    group_by(cusin) %>%
    summarize(max_viol = max(max_violations),
              mdn_viol = median(max_violations),
              mean_viol = mean(max_violations))

# Merge number of restaurants with number of violations by cuisine type
cuisine_violations = left_join(ncuisines, violations, by = "cusin")
  
    


```


Column {data-width=350}
-----------------------------------------------------------------------

### Percentage of Grades for Each Borough In NYC

```{r}
tidy_restaurant%>%
  select(boro, grade)%>%
  count(boro, grade)%>%
  mutate(boro = fct_reorder(boro, n))%>%
  spread(key = grade, value =n)%>%
  mutate(total= A+B+C,
         A = A/total*100,
         B = B/total*100,
         C = C/total*100)%>%
 plot_ly(x = ~boro, y = ~A, type = 'bar', name = 'Grade A')%>% 
  add_trace(y = ~B, name = 'Grade B') %>% 
  add_trace(y = ~C, name = 'Grade C') %>% 
  layout(title = "Percentage of Grades for Each Borough in NYC", yaxis = list(title = 'Percentage (%)'), barmode = "stack")
```

### Change of the Number of Grades in Time

```{r}
tidy_restaurant%>%
  mutate(date =  as.POSIXct(date),
         date = lubridate::floor_date(date, unit ="month"))%>%
  count(date, grade)%>%
  filter(date!='1900-01-01')%>%  
  plot_ly(x = ~date, y = ~n, type = 'scatter', mode = 'lines', color = ~grade)%>%
  layout(title = "Change of the Number of Grades in Time", yaxis = list(title = "Freq of Grades"), xaxis = list(title = "Time")) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Critical violations in year 2016

```{r critical_flags}
tidy_restaurant %>%
  filter(critical_flag != "Not Applicable" & year == 2016) %>%
  group_by(boro, month, critical_flag) %>%
  count() %>% 
  ungroup() %>%
  spread(key = critical_flag, value = n) %>%
  clean_names() %>% 
  mutate(pct_critical = 100 * (critical / (critical + not_critical)),
         pct_critical = round(pct_critical, 2)) %>%
  plot_ly (x = ~month, y = ~critical, type = "scatter", mode = "lines", color = ~boro) %>%
    layout(
      xaxis = list(title = "Month"),
      yaxis = list(title = "Total critical violations")
    )


```

### Number of restaurants by cuisine type and number of violations by a single restaurant

```{r scatter}

cuisine_violations %>%
  mutate(text_label = str_c("Cuisine: ", cusin, 
                            "\nNumber of restaurants: ", format(nresto, nsmall=1, big.mark = ","),
                            "\nMax violations: ", max_viol)) %>%
  plot_ly(x = ~max_viol, y = ~nresto, type = "scatter", mode = "markers",
          text = ~text_label) %>%
    layout(
      xaxis = list(title = "Number of restaurants per cuisine type"),
      yaxis = list(title = "Max violations by a restaurant")
    )


```
