---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(janitor)
library(forcats)
library(readr)
library(lubridate)
library(tidyverse)
library(stringr)
```

```{r get_data}
nyc_inspections = read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz",
                           col_types = "cccccccccccccccccc", na = c("NA", "N/A")) %>%
  clean_names() 

tidy_restaurant = nyc_inspections %>%  
  filter(grade %in% c("A", "B", "C") & 
       !boro %in% "Missing") %>% 
  # Also remove cuisine description
  filter(cuisine_description != " Not Listed/Not Applicable") %>%
  separate(inspection_date, into = c("date", "remove"), sep ="T")%>%
  select(-remove)%>%
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro),
         id = camis,
         cusin = cuisine_description,
         month = months(as.Date(date)),
         month = factor(month, levels = month.name),
         year = as.numeric(substr(date, 1, 4))) %>% 
  select(inspection_num, id, date, month, year, boro, grade, score, dba, 
         cusin, street, zipcode, violation_description, critical_flag, inspection_type,
         violation_code, action)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boros = tidy_restaurant %>% distinct(boro) %>% pull()
cuisines = tidy_restaurant %>% distinct(cusin) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")

# selectInput widget
selectInput("cuisine_choice", label = h3("Select cuisine type"),
            choices = cuisines, selected = "American")


## sliderInput widget

# radioButtons widget
grade_choice = tidy_restaurant %>% distinct(grade) %>% pull()

radioButtons("grade_choice", label = h3("Choose Grade"),
    choices = grade_choice, 
    selected = "A")



```


Row
-----------------------------------------------------------------------

### Percentage of Grades for Each Borough In NYC

```{r}

renderPlotly({
  tidy_restaurant%>%
    filter(cusin == input$cuisine_choice ) %>%
  select(boro, grade)%>%
  count(boro, grade)%>%
  mutate(boro = fct_reorder(boro, n))%>%
  spread(key = grade, value =n)%>%
  mutate(total= A+B+C,
         A = A/total*100,
         B = B/total*100,
         C = C/total*100)%>%
 plot_ly(x = ~boro, y = ~A, type = 'bar', name = 'Grade A')%>% 
  add_trace(y = ~B, name = 'Grade B') %>% 
  add_trace(y = ~C, name = 'Grade C') %>% 
  layout(title = "Percentage of Grades for Each Borough in NYC", yaxis = list(title = 'Percentage (%)'), barmode = "stack")
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Change of the Number of Grades in Time

```{r}
renderPlotly({tidy_restaurant%>%
  mutate(date =  as.POSIXct(date),
         date = lubridate::floor_date(date, unit ="month"))%>%
  count(date, grade)%>%
  filter(date!='1900-01-01')%>%  
  plot_ly(x = ~date, y = ~n, type = 'scatter', mode = 'lines', color = ~grade)%>%
  layout(title = "Change of the Number of Grades in Time", yaxis = list(title = "Freq of Grades"), xaxis = list(title = "Time")) })
```

###  Critical violations in year 2016

```{r}
renderPlotly({
  tidy_restaurant %>%
  filter(critical_flag != "Not Applicable" & year == 2016) %>%
  group_by(boro, month, critical_flag) %>%
  count() %>% 
  ungroup() %>%
  spread(key = critical_flag, value = n) %>%
  clean_names() %>% 
  mutate(pct_critical = 100 * (critical / (critical + not_critical)),
         pct_critical = round(pct_critical, 2)) %>%
  plot_ly (x = ~month, y = ~critical, type = "scatter", mode = "lines", color = ~boro) %>%
    layout(
      xaxis = list(title = "Month"),
      yaxis = list(title = "Total critical violations")
    )

})
```

### Number of restaurants by cuisine type and number of violations by a single restaurant
```{r}
renderPlotly({
  cuisine_violations %>%
  mutate(text_label = str_c("Cuisine: ", cusin, 
                            "\nNumber of restaurants: ", format(nresto, nsmall=1, big.mark = ","),
                            "\nMax violations: ", max_viol)) %>%
  plot_ly(x = ~max_viol, y = ~nresto, type = "scatter", mode = "markers",
          text = ~text_label) %>%
    layout(
      xaxis = list(title = "Number of restaurants per cuisine type"),
      yaxis = list(title = "Max violations by a restaurant")
    )
})
```

